services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: smartlinks_user
      POSTGRES_PASSWORD: smartlinks_password
      POSTGRES_DB: smartlinks_redirector
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redirector:
    image: redirector
    build:
      context: .
      dockerfile: Redirector/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - postgres
    volumes:
      - ~/.aspnet/https:/https:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=smartlinks_redirector;Username=smartlinks_user;Password=smartlinks_password
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${DEV_CERT_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
volumes:
  postgres_data: