// <auto-generated />
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Redirector;

#nullable disable

namespace Redirector.Migrations
{
    [DbContext(typeof(RedirectsDbContext))]
    [Migration("20241128183949_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Redirector.SmartLinkDescription", b =>
                {
                    b.Property<string>("LinkPath")
                        .HasColumnType("text");

                    b.Property<JsonElement>("Description")
                        .HasColumnType("jsonb");

                    b.HasKey("LinkPath");

                    b.ToTable("SmartLinkDescription");
                });
#pragma warning restore 612, 618
        }
    }
}
